### ISSUE TITLE
Puzzle Proposal - Moving Blocks

### ISSUE THREAD

**Issue by collectivenectar** [GDL-Collaborators/indigo#13]
DannyWebbie mentioned a possible issue is visual busyness compared to the other puzzles, which I admit I wasn't even considering when getting carried away designing it...so, I was thinking maybe  lowering the height of as many details whenever possible and keeping colors bright so it doesn't feel crowded. 

Maybe the moveable blocks could be a pale translucent material? Also, the 'doors' could instead be trap doors in the floor, if that makes it any cleaner visually. Maybe instead of having walls, the area contained by the walls could just be black space/water/deadly goop/etc.

Anyways, the area colored in red is open floor, and the area colored in blue are the moveable blocks. Blocks can't be moved in directions where there is an adjacent block, they can only be moved in a direction when there is space behind it. There are at least 5 opportunities I can think of where the player can screw themselves over by moving a block incorrectly.

![image0](https://user-images.githubusercontent.com/63463014/79344112-a9f7c800-7f2f-11ea-9a68-7a2898a433f4.jpg)

There are some additional changes I would make, since I realized that pressure plates 1 and 2 could just be switches, meaning they wouldn't need a whole room taking up space. The moveable block in the room where pressure plate 3 is doesn't really need to be there.

Pressure plate 1(which is now changed to a switch) opens door to pressure plate 2(also a switch now). Pressure plate 2 opens the door to pressure plate 3. Pressure plate 3 opens the door to the exit portal. Pressure plate 3 is the kind that requires constant 'pressure' to keep the door status as open.

**Comment by collectivenectar** [comment]
If it's just way too busy, can also just remove all the switches and plates, shrink the dimensions and make it just about the path through the blocks, like this :


![IMG_2172](https://user-images.githubusercontent.com/63463014/79350606-f810c980-7f37-11ea-92e9-cecfa2d7dd7f.jpg)

**Comment by collectivenectar** [comment]
![puzzle idea solution](https://user-images.githubusercontent.com/63463014/79363763-9dcc3480-7f48-11ea-92a9-e01fa8401973.jpg)

**Comment by strutcode** [comment]
I love it. It’d be great to have a simpler version to use as an introduction in an earlier level but I think this would be a perfect later stage puzzle.

**Comment by collectivenectar** [comment]
![IMG_2174](https://user-images.githubusercontent.com/63463014/79375043-4afa7900-7f58-11ea-9df6-2d95e5f6bbb0.jpg)
 Here's a shorter puzzle

**Comment by strutcode** [comment]
Both puzzles were added. Thanks @collectivenectar !
