### ISSUE TITLE
puzzle proposal - Cairn stones

### ISSUE THREAD

**Issue by collectivenectar** [GDL-Collaborators/indigo#15]
So going with the theme of stones, and the look of the portals, I thought maybe a puzzle with interaction being the theme could be good involving some simple cairn stones. There are the stones, an NPC, a lost item quest(pair of spectacles), a few non visible interactive spots on the floor, and I was thinking maybe for humor/levity a scribble of writing on one of the walls. Once the correct order of stones is executed, the portal activates.

Objects/interactions available in game level:

5(more or less) cairn stones - Each stone has a visible letter(could be in 'rune style' lettering, or literally a rune from runic futhark alphabet) and can be interacted with by touching. If it's simple, I'd like that the stones change color or have a visible indicator showing that the stones have been 'activated' --- For a perfectly similar example, consider the Diablo II cairn stone puzzle. Sound fx also optional(as each stone is pressed a simple one shot fx could play). The cairn sprites could even be cannibalized from the entering portal sprite?

Scribbles on the wall - Could be that someone has come through before and spent some time trying to come up with possible combinations, either just going through systematically (runes in alphabetical order 12345, 12354,12435, 12453, etc) or trying out words they could spell with the runes. The scribbles could be actually displayed at a readable size on screen, or as a zoomed image, or just in ui as text upon interaction.

NPC - Old Crone - Old Crone has lost her spectacles(glasses) and has already figured out the order, so she's willing to tell you if you can find them.

Possible dialogue:

-------
'Hello little one, you haven't seen a pair of spectacles around here, have you? I was in a trance, meditating on the solution, when a spirit took over my body. When I came to, I was crouched in that corner over there and my face was wet with tears...I suddenly knew the right order to activate the stones, but now I can't find my glasses. I'll tell you what--I'll make you a deal: If you can find them for me, I'll tell you the correct order.'

Interaction ends

Dialogue 2 if player has no glasses in inventory : 'Have you found them yet?'
Player dialogue option is only 'no'
'Well, keep looking, I'm sure you'll find them soon enough.'

Dialogue 3 if player has glasses in inventory : 'Where were they? Huh...I could have sworn I looked there thoroughly...how strange. Well, you've fulfilled your end of the deal, so now for my part: The correct order is '______''

------

Aside from this maybe just a few (not collision nodes though) zones with in the level that are not identifiable by the player visually, but when close enough the interact button becomes available. After interacting, only one of the spots when interacted with will generate a text display of 'Found a pair of spectacles,' while the other spots will display a 'There's nothing here but dust,' or, 'There's nothing here either. This area of the room is cold for no apparent reason,' etc.

That's it. Thoughts?

**Comment by strutcode** [comment]
Looks good to me! The assets shouldn't be hard to do and it makes use of the systems we have. My one alteration would be that we don't have multiple choice dialogue so we can just eliminate the player response.

**Comment by strutcode** [comment]
I believe we can call this done. Good work!
