### ISSUE TITLE
Premise

### ISSUE THREAD

**Issue by strutcode** [GDL-Collaborators/indigo#2]
In this thread let's pick a premise based on the selected genre:

## Adventure

Adventure could mean many things. Classic point and click adventure/puzzle games, action adventure, exploration adventure, or a story driven adventure epic in visual novel form.

To submit an idea, make sure it fits the following criteria:

1. Limit the description to an elevator pitch, a couple of sentences or about as much as you can say in 30 seconds
2. Don't include [Won't Add](https://github.com/GDL-Collaborators/indigo/projects/2) features
3. Make sure you provide at least a basic description of what the player will do

Use :+1: and :-1: reactions to vote for your favorite ideas!

**Comment by strutcode** [comment]
An undersea adventure to recover a long lost treasure. You have to balance your air supply against avoiding detection by the creatures of the deep.

**Comment by strutcode** [comment]
After finding a genie in a bottle who twists your wishes, you must travel through bizarre worlds and use your wits and weapons to get home.

**Comment by strutcode** [comment]
A murder mystery whodunit on a Martian colony in the 2300s. Uncovering clues and grilling witnesses and suspects is the order of the day.

**Comment by Xahell** [comment]
Climb the Ascension Tower, a mighty place of power, with your childhood friend. Each floor will challenge you with a unique puzzle. How far will you go to fulfill your dream?

**Comment by strutcode** [comment]
Following Discord discussion the consensus is:
* The goal is to climb the ascension tower
* Top down perspective
* Light puzzle solving
