### ISSUE TITLE
Player Interaction UX

### ISSUE THREAD

**Issue by strutcode** [GDL-Collaborators/indigo#6]
Some issues have already been solved but a few issues still remain with the player interaction system.

There should be some way for the player to understand and influence what they interact with. Currently the first object as determined by internal ordering is interacted with when there are multiple overlaps.

There should also be a player UI for interactable objects, perhaps something like this:

![image](https://user-images.githubusercontent.com/42973934/79049882-346cbe80-7bf4-11ea-9df7-c2abc76de41a.png)

![image](https://user-images.githubusercontent.com/42973934/79049887-3c2c6300-7bf4-11ea-8beb-36035b839831.png)

**Comment by Xahell** [comment]
It could also be a color change on the currently focused interactive element.

**Comment by strutcode** [comment]
It's hardly ideal but I think this is about as good as it's gonna get. Closing this one out.
